#!/usr/bin/env bash
# scripts/lab/student-env.sh — Phase 0
#
# Generate a per-student .env on stdout from a student id. Conflict-free port
# bindings and subnets are derived from a hash of the id, so two students on
# the same host can run side-by-side without manual coordination.
#
# Usage:
#   scripts/lab/student-env.sh jdoe              # print to stdout
#   scripts/lab/student-env.sh jdoe > .env.jdoe  # save
#   docker compose --env-file .env.jdoe up -d
#
# The generated file extends .env.example with student-specific overrides.
#
# Phase E4 caveat -- collision-free for SMALL classes only:
#   The slot is sha256(id) % 128. With 13+ students the birthday
#   paradox makes a collision likely. tests/test_student_env.py
#   includes a `test_known_collision_pair` that pins iris+jack as the
#   demonstrated colliding pair. If your class has more than ~10
#   students or a colliding pair, the operator must either pick
#   different IDs or hand-allocate the subnets/ports in the generated
#   .env. A stateful allocator with persisted slot reservations would
#   remove this limitation (tracked under Phase E in the implementation
#   plan if you want to upgrade it).

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <student-id>" >&2
    echo "  <student-id>: short, lowercase, alphanumeric (e.g. jdoe, alice42)" >&2
    exit 1
fi

STUDENT_ID="$1"

if [[ ! "$STUDENT_ID" =~ ^[a-z0-9]+([-_][a-z0-9]+)*$ ]]; then
    echo "[ERROR] STUDENT_ID '$STUDENT_ID' must match ^[a-z0-9]+([-_][a-z0-9]+)*$" >&2
    exit 2
fi

# Stable slot from the id. Constrained to 0..127 so that the derived third
# octet (slot * 2 + 1) stays within the legal 0..255 range and lab-net /
# quarantine-net always get a unique adjacent pair.
SLOT=$(( 0x$(printf '%s' "$STUDENT_ID" | sha256sum | cut -c1-4) % 128 ))

# Port offsets — start above 10000 so they don't collide with common system
# services. Each student reserves a contiguous block of 10 ports.
PORT_BASE=$(( 10000 + SLOT * 10 ))

# Subnet — second octet is fixed to 20 (matches default 172.20.0.x), third
# octet is the slot * 2 so lab-net and quarantine-net get adjacent /24s.
LAB_OCTET=$(( SLOT * 2 ))
QUARANTINE_OCTET=$(( SLOT * 2 + 1 ))

cat <<EOF
# -----------------------------------------------------------------------------
# Generated by scripts/lab/student-env.sh for student '${STUDENT_ID}'
# Slot ${SLOT} — derived from sha256("${STUDENT_ID}")
# -----------------------------------------------------------------------------

# Per-student isolation
STUDENT_ID=${STUDENT_ID}
COMPOSE_PROJECT_NAME=aib-${STUDENT_ID}
LAB_NET_PREFIX=172.20.${LAB_OCTET}
QUARANTINE_NET_PREFIX=172.20.${QUARANTINE_OCTET}

# Host port bindings
BLUE_TEAM_PORT=$(( PORT_BASE + 0 ))
SCOREBOARD_PORT=$(( PORT_BASE + 2 ))
KIBANA_PORT=$(( PORT_BASE + 1 ))
ELASTICSEARCH_PORT=$(( PORT_BASE + 3 ))
PKI_NGINX_PORT=$(( PORT_BASE + 4 ))

# The rest of the variables fall back to defaults baked into docker-compose.yml.
# If you need to override any (e.g. DB_PASS, SAFE_MODE_DOMAINS), append them
# below. See .env.example for the full list.
EOF
