#!/usr/bin/env bash
# =============================================================================
# Adversary-in-a-Box — undo a botched board bootstrap.
#
# Closes every issue whose title was generated by setup_project_board.sh
# ("[US-x.y]" or "[US-x.y][task]"), deletes our labels, and deletes the
# Project v2 board. Milestones are kept (they may have referenced issues
# in other tooling); pass DELETE_MILESTONES=1 to remove them too.
#
#   DRY_RUN=1 ./teardown_project_board.sh
#   DELETE_MILESTONES=1 ./teardown_project_board.sh
# =============================================================================
set -euo pipefail

REPO="${REPO:-voltron-1/Adversary-in-a-box}"
OWNER="${REPO%%/*}"
PROJECT_TITLE="${PROJECT_TITLE:-Adversary-in-a-Box}"
STORIES_FILE="${STORIES_FILE:-$(dirname "$0")/user_stories.yml}"
DRY_RUN="${DRY_RUN:-0}"
DELETE_MILESTONES="${DELETE_MILESTONES:-0}"

log() { printf '\033[36m[teardown]\033[0m %s\n' "$*"; }
die() { printf '\033[31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }
run() {
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '\033[35m[dry-run]\033[0m %q ' "$@"; printf '\n'
  else
    "$@"
  fi
}

command -v gh >/dev/null || die "missing dependency: gh"
command -v yq >/dev/null || die "missing dependency: yq"
command -v jq >/dev/null || die "missing dependency: jq"

[[ -f "$STORIES_FILE" ]] || die "stories file not found: $STORIES_FILE"

if [[ "$DRY_RUN" != "1" ]]; then
  gh auth status >/dev/null 2>&1 || die "run: gh auth login --scopes repo,project,read:org"
fi

# 1. Close issues matching our title prefixes.
log "closing generated issues..."
gh issue list --repo "$REPO" --state open --limit 500 \
    --search 'in:title "[US-"' --json number,title \
  | jq -r '.[] | "\(.number)\t\(.title)"' \
  | while IFS=$'\t' read -r n t; do
      log "  closing #$n  $t"
      run gh issue close "$n" --repo "$REPO" --reason "not planned"
    done

# 2. Delete labels owned by the bootstrap (every label declared in user_stories.yml).
log "deleting labels..."
yq -o=json '.labels | to_entries | .[].value | .[].name' "$STORIES_FILE" \
  | jq -r '.' \
  | while read -r name; do
      log "  deleting label: $name"
      run gh label delete "$name" --repo "$REPO" --yes || true
    done

# 3. Delete the Project v2.
log "deleting project..."
project_number=$(gh project list --owner "$OWNER" --format json \
  | jq -r --arg t "$PROJECT_TITLE" '.projects[] | select(.title==$t) | .number' || true)
if [[ -n "$project_number" && "$project_number" != "null" ]]; then
  log "  deleting project #$project_number"
  run gh project delete "$project_number" --owner "$OWNER"
else
  log "  no project named $PROJECT_TITLE"
fi

# 4. Optionally delete milestones.
if [[ "$DELETE_MILESTONES" == "1" ]]; then
  log "deleting milestones..."
  gh api "repos/$REPO/milestones?state=all" --jq '.[] | "\(.number)\t\(.title)"' \
    | while IFS=$'\t' read -r n t; do
        case "$t" in
          M[1-6]*)
            log "  deleting milestone #$n  $t"
            run gh api --method DELETE "repos/$REPO/milestones/$n" >/dev/null
            ;;
        esac
      done
fi

log "done."
